//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP323_Khachatryan_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCEntities : DbContext
    {
        public PCEntities()
            : base("name=PCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assembly> assemblies { get; set; }
        public virtual DbSet<basepart> baseparts { get; set; }
        public virtual DbSet<boardformfactorcase> boardformfactorcases { get; set; }
        public virtual DbSet<@case> cases { get; set; }
        public virtual DbSet<casesize> casesizes { get; set; }
        public virtual DbSet<certificate> certificates { get; set; }
        public virtual DbSet<cpu> cpus { get; set; }
        public virtual DbSet<fandimension> fandimensions { get; set; }
        public virtual DbSet<formfactor> formfactors { get; set; }
        public virtual DbSet<gpu> gpus { get; set; }
        public virtual DbSet<gpuinterface> gpuinterfaces { get; set; }
        public virtual DbSet<hdd> hdds { get; set; }
        public virtual DbSet<igpu> igpus { get; set; }
        public virtual DbSet<manufacturer> manufacturers { get; set; }
        public virtual DbSet<memorytype> memorytypes { get; set; }
        public virtual DbSet<motherboard> motherboards { get; set; }
        public virtual DbSet<partassembly> partassemblies { get; set; }
        public virtual DbSet<parttype> parttypes { get; set; }
        public virtual DbSet<powersupply> powersupplies { get; set; }
        public virtual DbSet<processorcooler> processorcoolers { get; set; }
        public virtual DbSet<ram> rams { get; set; }
        public virtual DbSet<socket> sockets { get; set; }
        public virtual DbSet<socketprocessorcooler> socketprocessorcoolers { get; set; }
        public virtual DbSet<ssd> ssds { get; set; }
        public virtual DbSet<storagedevice> storagedevices { get; set; }
        public virtual DbSet<storagedeviceinterface> storagedeviceinterfaces { get; set; }
        public virtual DbSet<storagedevicetype> storagedevicetypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<videoconnector> videoconnectors { get; set; }
        public virtual DbSet<videoconnectorgpu> videoconnectorgpus { get; set; }
    }
}
